# Generated by Django 3.1.7 on 2021-02-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
