# Generated by Django 3.1.7 on 2021-02-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
        ('users', '0005_auto_20210220_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='elections',
            field=models.ManyToManyField(to='voting.Election'),
        ),
        migrations.AddField(
            model_name='voter',
            name='elections',
            field=models.ManyToManyField(to='voting.Election'),
        ),
    ]
