# Generated by Django 3.1.7 on 2021-02-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='expiry_date',
            field=models.DateField(default="2001-12-12"),
            preserve_default=False,
        ),
    ]
